/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package text_editor;

import java.util.ArrayList;
import javax.swing.text.AttributeSet;
import javax.swing.text.Style;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Yosua Blanco Diaz
 */
public class Interface extends javax.swing.JFrame {
    //JTextPane : campo de texto
    /**
     * Creates new form Interface
     */ 
    public Interface() {
        initComponents();
        this.originator = new Originator(JTextPane.getStyledDocument());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        sameAsButton = new javax.swing.JButton();
        colorButton = new javax.swing.JButton();
        undoButton = new javax.swing.JButton();
        redoButton = new javax.swing.JButton();
        copyButton = new javax.swing.JButton();
        cutButton = new javax.swing.JButton();
        pasteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Text Editor");

        createButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add-file.png"))); // NOI18N
        createButton.setMnemonic('C');
        createButton.setToolTipText("Crear");
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonMouseClicked(evt);
            }
        });
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        openButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/open-folder-with-document.png"))); // NOI18N
        openButton.setToolTipText("Abrir");
        openButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openButtonMouseClicked(evt);
            }
        });

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/save-file.png"))); // NOI18N
        saveButton.setToolTipText("Guardar");
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
        });
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        sameAsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/save as-file.png"))); // NOI18N
        sameAsButton.setToolTipText("Guardar como");
        sameAsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sameAsButtonMouseClicked(evt);
            }
        });

        colorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/resaltador.png"))); // NOI18N
        colorButton.setToolTipText("Remarcar");
        colorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorButtonMouseClicked(evt);
            }
        });
        colorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButtonActionPerformed(evt);
            }
        });

        undoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/undo.png"))); // NOI18N
        undoButton.setToolTipText("Ctrl + Z");
        undoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                undoButtonMouseClicked(evt);
            }
        });

        redoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/redo.png"))); // NOI18N
        redoButton.setToolTipText("Ctrl + Y");
        redoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redoButtonMouseClicked(evt);
            }
        });

        copyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/copiar.png"))); // NOI18N
        copyButton.setToolTipText("Copiar");
        copyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                copyButtonMouseClicked(evt);
            }
        });
        copyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyButtonActionPerformed(evt);
            }
        });

        cutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cortar-con-tijeras.png"))); // NOI18N
        cutButton.setToolTipText("Cortar");
        cutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cutButtonMouseClicked(evt);
            }
        });
        cutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutButtonActionPerformed(evt);
            }
        });

        pasteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pegar.png"))); // NOI18N
        pasteButton.setToolTipText("Pegar");
        pasteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pasteButtonMouseClicked(evt);
            }
        });
        pasteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteButtonActionPerformed(evt);
            }
        });

        JTextPane.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTextPaneKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(JTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sameAsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(undoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pasteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(copyButton)
                    .addComponent(cutButton)
                    .addComponent(pasteButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(createButton)
                        .addComponent(openButton)
                        .addComponent(saveButton)
                        .addComponent(sameAsButton)
                        .addComponent(colorButton)
                        .addComponent(undoButton)
                        .addComponent(redoButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
        );

        createButton.getAccessibleContext().setAccessibleName("crear");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    private void copyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copyButtonActionPerformed

    private void cutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cutButtonActionPerformed

    private void pasteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasteButtonActionPerformed

    private void createButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseClicked
        Command myCommand = new CreateCommand(this.JTextPane);
        myCommand.execute();
    }//GEN-LAST:event_createButtonMouseClicked

    private void openButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openButtonMouseClicked
        Command myCommand = new OpenCommand(this.JTextPane);
        myCommand.execute();
        originator = new Originator(JTextPane.getStyledDocument());
        name = myCommand.getName();
        doc = myCommand.getDoc();
    }//GEN-LAST:event_openButtonMouseClicked

    private void saveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseClicked
        Command myCommand = new SaveCommand(this.JTextPane, JTextPane.getStyledDocument(), estilo, name);
        myCommand.execute();
        originator = new Originator(JTextPane.getStyledDocument());
        name = myCommand.getName();
    }//GEN-LAST:event_saveButtonMouseClicked

    private void sameAsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sameAsButtonMouseClicked
        Command myCommand = new SaveAsCommand(this.JTextPane, JTextPane.getStyledDocument(), estilo, name);
        myCommand.execute();
        originator = new Originator(JTextPane.getStyledDocument());
        name = myCommand.getName();
    }//GEN-LAST:event_sameAsButtonMouseClicked

    private void colorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorButtonMouseClicked
        doc = JTextPane.getStyledDocument();
        estilo = JTextPane.addStyle("miEstilo", null);
        Command myCommand = new ColorCommand(this.JTextPane,doc,estilo);
        myCommand.execute();
    }//GEN-LAST:event_colorButtonMouseClicked

    private void undoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_undoButtonMouseClicked
        Command myCommand = new UndoCommand(this.JTextPane, originator);
        myCommand.execute();
    }//GEN-LAST:event_undoButtonMouseClicked

    private void redoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redoButtonMouseClicked
        Command myCommand = new RedoCommand(this.JTextPane, originator);
        myCommand.execute();
    }//GEN-LAST:event_redoButtonMouseClicked

    private void cutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutButtonMouseClicked
        Command myCommand = new CutCommand(this.JTextPane);
        myCommand.execute();
        Text = myCommand.getText();
        attributes = myCommand.getAtrributes();
    }//GEN-LAST:event_cutButtonMouseClicked

    private void copyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copyButtonMouseClicked
        Command myCommand = new CopyCommand(this.JTextPane);
        myCommand.execute();
        Text = myCommand.getText();
        attributes = myCommand.getAtrributes();
    }//GEN-LAST:event_copyButtonMouseClicked

    private void pasteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pasteButtonMouseClicked
        Command myCommand = new PasteCommand(this.JTextPane, Text, attributes);
        myCommand.execute();
    }//GEN-LAST:event_pasteButtonMouseClicked

    private void colorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorButtonActionPerformed

    private void JTextPaneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextPaneKeyTyped
        
    }//GEN-LAST:event_JTextPaneKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }
    
    StyledDocument doc;
    Style estilo;
    String Text="";
    protected ArrayList<AttributeSet> attributes = new ArrayList<>();
    String name="";
    Originator originator;
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane JTextPane;
    private javax.swing.JButton colorButton;
    private javax.swing.JButton copyButton;
    private javax.swing.JButton createButton;
    private javax.swing.JButton cutButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton openButton;
    private javax.swing.JButton pasteButton;
    private javax.swing.JButton redoButton;
    private javax.swing.JButton sameAsButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton undoButton;
    // End of variables declaration//GEN-END:variables

    
}
